### ISSUE TITLE
Doua chitante cu aceeasi serie si aceelasi numar

### ISSUE THREAD

**Issue by SebiAlecu** [SoftulmeuRo/maparomfacturare#1]
Pasul 1: In ecranul chitante, folosind butonul adauga vreau sa adaug o chitanta noua
![image](https://cloud.githubusercontent.com/assets/12894907/8475135/451657dc-20be-11e5-8171-95992d36347c.png)

Pasul 2: Am selectat o factura
![image](https://cloud.githubusercontent.com/assets/12894907/8475152/73c259be-20be-11e5-8a7a-997ccfcb3078.png)

Pasul 3: Dupa selectarea facturii s-au introdus automat datele: client, serie factura, numar factura, data factura si tva. Manual am introdus datele in chitanta, respectiv: serie chitanta, numar chitanta, suma, suma in litere si explicatia. Apoi am salvat chitanta folosind butonul salveaza.
![image](https://cloud.githubusercontent.com/assets/12894907/8475502/27115fea-20c1-11e5-9c2a-e62966308caa.png)

Pasul 4: In ecranul facturi am adaugat o factura noua folosit butonul adauga:
![image](https://cloud.githubusercontent.com/assets/12894907/8475292/a95ef036-20bf-11e5-90dc-10bee1319a87.png)

Pasul 5: Am completat factura
![image](https://cloud.githubusercontent.com/assets/12894907/8475529/57e09258-20c1-11e5-81a3-0b259305bc5f.png)

Pasul 6: Am dorit sa generez automat chitanta folosind butonul "Genereaza chitanta cu toata suma"
![image](https://cloud.githubusercontent.com/assets/12894907/8475394/56eac1da-20c0-11e5-9698-dbd672284038.png)

Pasul 7: Chitanta generata automat are aceelasi numar si aceeasi serie cu cea introdusa manual la pasul 3
![image](https://cloud.githubusercontent.com/assets/12894907/8475460/c82da754-20c0-11e5-850b-123e08b0ed47.png)

Pasul 8: Doua chitante cu aceeasi serie, aceelasi numar si aceeasi data
![image](https://cloud.githubusercontent.com/assets/12894907/8475489/f6167c22-20c0-11e5-80cb-e8107cad7757.png)

**Comment by t1b1c** [comment]
rezolvat pls verifica si inchide daca e cazul
